# .streamlit/config.toml

# ======== ATIVO: Pro Light (estilo iCloud) ========
[theme]
base = "light"
primaryColor = "#1F4FFF"                # azul Apple-like
backgroundColor = "#F6F7FB"             # fundo suave
secondaryBackgroundColor = "#FFFFFF"    # cards "glass"
textColor = "#1B1B1F"
font = "sans serif"                     # "sans serif", "serif" ou "monospace"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false


# ======== OPCIONAL: Pro Dark (descomente este bloco e comente o [theme] acima) ========
# [theme]
# base = "dark"
# primaryColor = "#6690FF"
# backgroundColor = "#0F1115"
# secondaryBackgroundColor = "#171A21"
# textColor = "#E6E8EF"
# font = "sans serif"


# ======== OPCIONAL: Alto Contraste (acessibilidade) ========
# [theme]
# base = "light"
# primaryColor = "#0B57D0"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F2F4F8"
# textColor = "#101114"
# font = "sans serif"
